//------------------------------------------------------------------------------
// <auto-generated>
//      This file is auto-generated!
//      DO NOT MODIFY!
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Diagnostics.CodeAnalysis;

namespace CPF.CefGlue.Interop
{
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "133.4.9+ge3b12aa+chromium-133.0.6943.127";
        public const int CEF_VERSION_MAJOR = 133;
        public const int CEF_COMMIT_NUMBER = 3138;
        public const string CEF_COMMIT_HASH = "e3b12aa90581ba5e667b83540f7c5ae3a9128cad";
        
        public const int CHROME_VERSION_MAJOR = 133;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 6943;
        public const int CHROME_VERSION_PATCH = 127;
        
    }
}
